name: Automerge

on:
  push:
    branches:
      - "main"

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Merge main -> alpha
        uses: devmasx/merge-branch@main
        with:
          type: now
          target_branch: alpha
          github_token: ${{ secrets.GITHUB_TOKEN }}
          